# Numpy

>Num - Numerical, Py - Python

> It is one of the most important libraries in Python for numerical computations.

>It is the backbone of Machine Learning in Python.

>They store data of similar datatypes only.

>Numpy consists of two parts:

>>ndarray: n-dimensional array

>>Ufunc: Universal functions

# ndarray

In [1]:
import numpy as np
np.__version__

'1.21.2'

In [2]:
l = [1, 2.32,"Darshan",5-9j]
l

[1, 2.32, 'Darshan', (5-9j)]

In [55]:
a = 10
b = 20
print(a)
print(b)

10
20


In [6]:
# np.array(data, dtype)

arr = np.array([10,20,30,40,50], dtype='int')
print(arr)
print(type(arr))
print(arr.dtype)

[10 20 30 40 50]
<class 'numpy.ndarray'>
int64


In [7]:
# np.array(data, dtype)

arr = np.array([10,20,30,40,50])
print(arr)
print(type(arr))
print(arr.dtype)

[10 20 30 40 50]
<class 'numpy.ndarray'>
int64


In [8]:
# np.array(data, dtype)

arr = np.array([10,20,30.0,40,50])
print(arr)
print(type(arr))
print(arr.dtype)

[10. 20. 30. 40. 50.]
<class 'numpy.ndarray'>
float64


In [9]:
# np.array(data, dtype)

arr = np.array([10,20,30.0,9+6j,50])
print(arr)
print(type(arr))
print(arr.dtype)

[10.+0.j 20.+0.j 30.+0.j  9.+6.j 50.+0.j]
<class 'numpy.ndarray'>
complex128


In [19]:
# np.array(data, dtype)

arr = np.array([10,20,30.0,9+6j,50,"Darshan"])
print(arr)
print(type(arr))
print(arr.dtype)

['10' '20' '30.0' '(9+6j)' '50' 'Darshan']
<class 'numpy.ndarray'>
<U64


In [23]:
# np.array(data, dtype)

arr = np.array([10,20,30,40,50])
print(arr)
print(type(arr))
print(arr.dtype)
print(np.ndim(arr))
print(np.sum(arr))
print(np.mean(arr))
print(np.min(arr))
print(np.max(arr))
print(np.median(arr))
print(np.var(arr))
print(np.std(arr))
# Indexing
print(arr[0])
# Slicing
print(arr[1:3]) # SI=1, EI=3-1

[10 20 30 40 50]
<class 'numpy.ndarray'>
int64
1
150
30.0
10
50
30.0
200.0
14.142135623730951
10
[20 30]


In [24]:
# np.array(data, dtype)

arr = np.array((10,20,30,40,50))
print(arr)
print(type(arr))
print(arr.dtype)
print(np.ndim(arr))
print(np.sum(arr))
print(np.mean(arr))
print(np.min(arr))
print(np.max(arr))
print(np.median(arr))
print(np.var(arr))
print(np.std(arr))
# Indexing
print(arr[0])
# Slicing
print(arr[1:3]) # SI=1, EI=3-1

[10 20 30 40 50]
<class 'numpy.ndarray'>
int64
1
150
30.0
10
50
30.0
200.0
14.142135623730951
10
[20 30]


__Numpy is used for Numerical Computations. So it would be foolish enough of us if we store anything other than numbers in a numpy array.__

In [28]:
# np.array(data, dtype)

arr = np.array([[10,20],[30,40],[50,60]])
print(arr)
print(type(arr))
print(arr.dtype)
print(np.ndim(arr))
print(arr.shape)
print(np.sum(arr))
print(np.mean(arr))
print(np.min(arr))
print(np.max(arr))
print(np.median(arr))
print(np.var(arr))
print(np.std(arr))
# Indexing
print(arr[0])
print(arr[0][1])
# Slicing
print(arr[1:3]) # SI=1, EI=3-1

[[10 20]
 [30 40]
 [50 60]]
<class 'numpy.ndarray'>
int64
2
(3, 2)
210
35.0
10
60
35.0
291.6666666666667
17.07825127659933
[10 20]
20
[[30 40]
 [50 60]]


In [29]:
np.zeros([2,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [30]:
np.zeros([2,4], dtype='int')

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [31]:
np.ones([2,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [32]:
np.ones([12,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [34]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [36]:
b = np.zeros_like(a)
b

array([[0, 0],
       [0, 0]])

In [37]:
c = np.ones_like(a)
c

array([[1, 1],
       [1, 1]])

In [51]:
np.random.rand(3,4)

array([[0.70441884, 0.88372556, 0.71843641, 0.82605726],
       [0.183607  , 0.41953043, 0.93279644, 0.06758376],
       [0.90058392, 0.51755427, 0.17273462, 0.07888666]])

In [65]:
import time
time.time()

1632149878.43457

In [68]:
for i in range(25):
    print(time.time(), end=" | ")
    time.sleep(0.5)

1632149943.273789 | 1632149943.778419 | 1632149944.283704 | 1632149944.7859159 | 1632149945.291164 | 1632149945.7963982 | 1632149946.2967649 | 1632149946.8018959 | 1632149947.3043468 | 1632149947.809708 | 1632149948.31511 | 1632149948.819105 | 1632149949.320804 | 1632149949.822935 | 1632149950.328 | 1632149950.829586 | 1632149951.330967 | 1632149951.8363578 | 1632149952.338512 | 1632149952.84061 | 1632149953.342061 | 1632149953.846443 | 1632149954.351716 | 1632149954.854815 | 1632149955.355844 | 

In [69]:
initial_time = time.time()
sum = 0
for i in range(999999999):
    sum = sum+0
end_time = time.time()
print(end_time-initial_time)

73.39770269393921


# Speed of Numpy vs Python

In [72]:
# importing required packages
import numpy
import time

# size of arrays and lists
size = 99000000

# declaring lists
list1 = range(size)
list2 = range(size)

# declaring arrays
array1 = numpy.arange(size)
array2 = numpy.arange(size)

# list
initialTime = time.time()
resultantList = [(a * b) for a, b in zip(list1, list2)]

# calculating execution time
print("Time taken by Lists :",
	(time.time() - initialTime),
	"seconds")

# NumPy array
initialTime = time.time()
resultantArray = array1 * array2

# calculating execution time
print("Time taken by NumPy Arrays :",
	(time.time() - initialTime),
	"seconds")


Time taken by Lists : 8.107028007507324 seconds
Time taken by NumPy Arrays : 1.131500005722046 seconds


__Why are numpy faster?__

Numpy has vectorized functions i.e. all of numpy function's body is written in C++.

In [74]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [75]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [76]:
a.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [77]:
np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [78]:
np.arange(12).reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [79]:
np.arange(12).reshape(6,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [80]:
np.arange(12).reshape(2,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [82]:
np.arange(12).reshape(12,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [83]:
np.arange(12).reshape(1,12)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [85]:
np.arange(12).reshape(2,2,3)
# 2 arrays, of 2rows and 3cols

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

## Ufunc

It supports Broadcasting.

In [86]:
arr = np.arange(15).reshape(3,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [87]:
arr + 5

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [88]:
arr * 2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [89]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [91]:
# Transpose of a Matrix
arr_t = arr.T
arr_t

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [92]:
# Matrix Multiplication
# (mxp) * (pxn) = (mxn)

arr.dot(arr_t)

array([[ 30,  80, 130],
       [ 80, 255, 430],
       [130, 430, 730]])

In [93]:
a = np.array([[7,5,-3],[3,-5,2],[5,3,-7]])
b = np.array([16,-8,0])
np.linalg.solve(a,b)

array([1., 3., 2.])

In [94]:
# Inverse of a Matrix
# https://www.mathsisfun.com/algebra/matrix-inverse.html

Y = np.array([[1,2],[3,4]])
np.linalg.inv(Y)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [95]:
# Determinant
np.linalg.det(Y)

-2.0000000000000004

# Pandas

It is an important library for Data Manipulation, Data Wrangling and Data Analysis.

All the data representation in pandas is done in two primary data structures:

>Series: 1D ndarray with an axis label.

>DataFrame: 2D ndarray

# Series

In [96]:
import pandas as pd
pd.__version__

'1.2.4'

In [97]:
population = {
    'California' : 54343232,
    'Texas' : 54343232,
    'New York' : 4635332,
    'Florida' : 546331,
    'Illinois' : 645634
}
population

{'California': 54343232,
 'Texas': 54343232,
 'New York': 4635332,
 'Florida': 546331,
 'Illinois': 645634}

In [98]:
# pd.Series(data, index)
pd.Series([2,4,6])

0    2
1    4
2    6
dtype: int64

In [99]:
pd.Series([2,4,6], index=['A','B','C'])

A    2
B    4
C    6
dtype: int64

In [104]:
s = pd.Series(population)
print(s)
print(type(s))
print(s.index) # index is an attribute
print(s.values)
print(s.shape)

California    54343232
Texas         54343232
New York       4635332
Florida         546331
Illinois        645634
dtype: int64
<class 'pandas.core.series.Series'>
Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')
[54343232 54343232  4635332   546331   645634]
(5,)


In [105]:
# pd.DataFrame(data, index, columns)
df = pd.DataFrame(s)
df

0
California  54343232
Texas       54343232
New York     4635332
Florida       546331
Illinois      645634

In [106]:
df.shape

(5, 1)

In [107]:
df.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [108]:
df.values

array([[54343232],
       [54343232],
       [ 4635332],
       [  546331],
       [  645634]])

In [113]:
# pd.DataFrame(data, index, columns)
df = pd.DataFrame(s, columns=['Population'])
df

Population
California    54343232
Texas         54343232
New York       4635332
Florida         546331
Illinois        645634

In [114]:
# pd.DataFrame(data, index, columns)
df = pd.DataFrame(s)
df

0
California  54343232
Texas       54343232
New York     4635332
Florida       546331
Illinois      645634

In [115]:
df.columns

RangeIndex(start=0, stop=1, step=1)

In [116]:
df.columns = ['Population']
df

Population
California    54343232
Texas         54343232
New York       4635332
Florida         546331
Illinois        645634

In [117]:
df.reset_index()

index  Population
0  California    54343232
1       Texas    54343232
2    New York     4635332
3     Florida      546331
4    Illinois      645634

In [118]:
df

Population
California    54343232
Texas         54343232
New York       4635332
Florida         546331
Illinois        645634

In [119]:
df = df.reset_index()
df

index  Population
0  California    54343232
1       Texas    54343232
2    New York     4635332
3     Florida      546331
4    Illinois      645634

In [120]:
df.columns

Index(['index', 'Population'], dtype='object')

In [121]:
df.columns = ['State', 'Population']
df

State  Population
0  California    54343232
1       Texas    54343232
2    New York     4635332
3     Florida      546331
4    Illinois      645634

In [122]:
df = df.set_index('Population')

In [123]:
df

State
Population            
54343232    California
54343232         Texas
4635332       New York
546331         Florida
645634        Illinois

In [124]:
df.columns

Index(['State'], dtype='object')

In [125]:
df.index

Int64Index([54343232, 54343232, 4635332, 546331, 645634], dtype='int64', name='Population')

In [126]:
df.values

array([['California'],
       ['Texas'],
       ['New York'],
       ['Florida'],
       ['Illinois']], dtype=object)

In [128]:
df = pd.DataFrame({
    'Name' : ["Darshan","Naresh","Rahul","Kishor","Kamal"],
    "Salary" : [12000, 12321,10000, 8000,14000]
})
df

Name  Salary
0  Darshan   12000
1   Naresh   12321
2    Rahul   10000
3   Kishor    8000
4    Kamal   14000

In [129]:
df.Name

0    Darshan
1     Naresh
2      Rahul
3     Kishor
4      Kamal
Name: Name, dtype: object

In [130]:
df['Name']

0    Darshan
1     Naresh
2      Rahul
3     Kishor
4      Kamal
Name: Name, dtype: object

In [131]:
df.Salary

0    12000
1    12321
2    10000
3     8000
4    14000
Name: Salary, dtype: int64

In [132]:
df['Salary']

0    12000
1    12321
2    10000
3     8000
4    14000
Name: Salary, dtype: int64

In [133]:
df

Name  Salary
0  Darshan   12000
1   Naresh   12321
2    Rahul   10000
3   Kishor    8000
4    Kamal   14000

In [135]:
df.columns = ['Employee Name', 'Salary']
df

Employee Name  Salary
0       Darshan   12000
1        Naresh   12321
2         Rahul   10000
3        Kishor    8000
4         Kamal   14000

In [137]:
df['Employee Name']

0    Darshan
1     Naresh
2      Rahul
3     Kishor
4      Kamal
Name: Employee Name, dtype: object

# Read a csv file

In [138]:
df = pd.read_csv("student_records.csv")
df

Name OverallGrade Obedient  ResearchScore  ProjectScore Recommend
0   Henry            A        Y             90            85       Yes
1    John            C        N             85            51       Yes
2   David            F        N             10            17        No
3  Holmes            B        Y             75            71        No
4  Marvin            E        N             20            30        No
5   Simon            A        Y             92            79       Yes
6  Robert            B        Y             60            59        No
7   Trent            C        Y             75            33        No

In [139]:
df = pd.read_csv("https://raw.githubusercontent.com/ingledarshan/BoardInfinity/main/student_records.csv")
df

Name OverallGrade Obedient  ResearchScore  ProjectScore Recommend
0   Henry            A        Y             90            85       Yes
1    John            C        N             85            51       Yes
2   David            F        N             10            17        No
3  Holmes            B        Y             75            71        No
4  Marvin            E        N             20            30        No
5   Simon            A        Y             92            79       Yes
6  Robert            B        Y             60            59        No
7   Trent            C        Y             75            33        No

# Happy Learning